# Generated by Django 5.1.6 on 2025-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
