# Generated by Django 5.1.6 on 2025-09-17 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_delete_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="text",
            new_name="description",
        ),
    ]
