# Generated by Django 5.1.6 on 2025-03-27 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="descritption",
            new_name="description",
        ),
    ]
